spring:
  config:
    import: optional:configserver:http://localhost:7071
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/majorproj_ecom
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  server:
  port: 8081  
     
  
