spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/majorproj_ecom
    username: root
    password: root 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
    database-platform: org.hibernate.dialect.MySQL5Dialect
  boot:
    admin:
      client:
        url: http://localhost:1111/   
management:
  endpoints:
    web:
      exposure:
        include: '*'
    
    
server:
  port: 8081
        
     
  
