spring:
  boot:
    admin:
      client:
        url: http://localhost:1111/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/majorproj_ecom
    username: root
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
      
server:
  port: 8888    
  
#Application Messages
auth-service:
 messages:
  userReg: User Created
  userRegErr: User Creation Failed
  login: Logged In Successfully
  logInErr: Invalid Credentials
           
     
  
